export const CV = {
  name: "Felix Tellmann",
  address: "Cape Town, Vredehoek 8001, South Africa",
  email: "hello@flext.dev",
  mobile: "+27760313590",
  eduction: [
    {
      dateFrom: "1992",
      dateTo: "1996",
      city: "Mönchengladbach",
      country: "Germany",
      institution: "Primary School Gertraudenstraße",
      certificate: "Primary School Certificate",
      level: "School",
    },
    {
      dateFrom: "1996",
      dateTo: "2002",
      city: "Mönchengladbach",
      country: "Germany",
      institution: "Comprehensive School Espenstraße",
      certificate: "Secondary School Certificate",
      level: "School",
    },
    {
      dateFrom: "2002",
      dateTo: "2004",
      city: "Mönchengladbach",
      country: "Germany",
      institution: "Vocational College of Technology and Media",
      certificate: "High School Certificate",
      level: "School",
    },
    {
      dateFrom: "2008",
      dateTo: "2008",
      city: "Cape Town",
      country: "South Africa",
      institution: "International Hotel School",
      certificate: "Skills, Tasks and Result Training Certificate",
      level: "Higher Education",
    },
    {
      dateFrom: "2009",
      dateTo: "2012",
      city: "Cape Town",
      country: "South Africa",
      institution: "International Hotel School",
      certificate: "Higher Diploma in Professional Cookery & Kitchen Management",
      level: "Higher Education",
    },
    {
      dateFrom: "2009",
      dateTo: "2012",
      city: "Cape Town",
      country: "South Africa",
      institution: "International Hotel School",
      certificate: "Higher Diploma in Food & Beverage Management",
      level: "Higher Education",
    },
    {
      dateFrom: "2013",
      dateTo: "2013",
      city: "Cape Town",
      country: "South Africa",
      institution: "International Hotel School",
      certificate: "Higher Diploma in Hospitality Management",
      level: "Higher Education",
    },
    {
      dateFrom: "2015",
      dateTo: "2015",
      city: "Cape Town",
      country: "South Africa",
      institution: "University of Cape Town",
      certificate: "Postgraduate Diploma in Business Management & Entrepreneurship",
      level: "Higher Education",
    },
  ],
};
